FROM node:16

# Installing libvips-dev for sharp Compatability
RUN apt-get update && apt-get install libvips-dev -y

ENV NODE_ENV=production

WORKDIR /opt/

COPY ./package.json ./yarn.lock ./

ENV PATH /opt/node_modules/.bin:$PATH

RUN yarn config set network-timeout 600000 -g && yarn install
WORKDIR /opt/app
COPY ./ .
RUN yarn build

# Configure SSH for Azure App Service access
RUN apk add openssh \
     && echo "root:Docker!" | chpasswd

COPY sshd_config /etc/ssh/

RUN mkdir -p /tmp
COPY ssh_setup.sh /tmp
RUN chmod +x /tmp/ssh_setup.sh \
    && (sleep 1;/tmp/ssh_setup.sh 2>&1 > /dev/null)

EXPOSE 80 2222

CMD ["bash", "start_container.sh"]
