name: WebApp - Test

on:
  push:
    branches:
    - main
    paths:
    - ./frontend
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      containerAppName: cms-azsplatform-app
      imageName: azsstrapi
      resourceGroup: cms-azsplatform-app
    secrets:
      publishProfile: ${{ secrets.AZURE_WEBAPP_TEST_PUBLISH_PROFILE }}
      googleAnalytics: ${{ secrets.GOOGLE_ANALYTICS_TEST_ENV }}
