name: Web - Image Build

on:
  pull_request:
     branches:
     - '**'
  push:
    branches:
    - main
    - containerApps
    paths:
    - ./backend
    - ./frontend
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: docker login
        uses: docker/login-action@v1.10.0
        with:
          registry: azscjacr.azurecr.io
          username: ${{ secrets.AZURE_ACR_USER }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}
      - name: docker build
        working-directory: .
        run: |
          docker build -t azscjacr.azurecr.io/azsweb:${{ github.run_number }} -f web.dockerfile .
          
      - name: docker push
        run: |
          docker push --all-tags azscjacr.azurecr.io/azsweb
      
    
