name: Strapi Image Build

on:
  push:
    branches: [ main ]
    paths:
    - ./backend
    - ./frontend
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: docker login
        uses: docker/login-action@v1.10.0
        with:
          registry: azscjacr.azurecr.io
          username: ${{ secrets.AZURE_ACR_USER }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}
      - name: docker build
        working-directory: .
        run: |
          docker build -t azscjacr.azurecr.io/azsweb:${{ github.run_number }} .
          docker image tag azscjacr.azurecr.io/azsweb:${{ github.run_number }} azscjacr.azurecr.io/azsweb:latest
          
      - name: docker push
        run: |
          docker push --all-tags azscjacr.azurecr.io/azsweb
      
    
