name: Strapi - common

on:
  workflow_call:
    inputs:
      imageName:
        type: string
        required: true
      webAppName:
        type: string
        required: true
    secrets:
      azCliCreds:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.azCliCreds }}

    - name: Get latest tag
      id: latestTag
      run: |
        # Take the top 2 to make sure the tag 'latest' is coming in, as well as last number.
        # Then query to remove the tag 'latest'.
        # Then take the first item from the array, in case we have two numbers and no tag with 'latest'.
        $arr=$(az acr repository show-tags -n azscjacr --repository ${{ inputs.imageName }} --top 2 --orderby time_desc --query "[?!contains(@, 'latest')]" -o tsv) 
        tag=$arr[0]
        echo "Latest tag found: ${tag}"
        echo "tag=${tag}" >> "$GITHUB_OUTPUT"

    - name: Set image to container app
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.webAppName }}
        images: ${{ inputs.imageName }}
