name: Terraform Infrastructure

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_SP_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SP_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SP_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZ_SP_TENANT_ID }}
      TF_VAR_YT_API_KEY: ${{ secrets.YT_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_SP_ID }}","clientSecret":"${{ secrets.AZURE_SP_SECRET }}","subscriptionId":"${{ secrets.AZ_SP_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZ_SP_TENANT_ID }}"}'
          enable-AzPSSession: true
        
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - name: Terraform Version
        run: terraform version
        working-directory: ./infra
        
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra

      - name: Terraform apply
        run: terraform apply -auto-approve
        working-directory: ./infra
