name: Terraform Infrastructure

on:
  push:
    branches: [ main ]
    paths:
    - ./infra
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

env:
  ARM_CLIENT_ID: ${{ secrets.AZ_SP_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZ_SP_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SP_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZ_SP_TENANT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: printenv | grep ARM_CLIENT_ID
    
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4

      - name: Terraform Version
        run: terraform version
        working-directory: ./infra
        
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra

      - name: Terraform apply
        run: terraform apply
        working-directory: ./infra
