name: Strapi - Deploy to Prods

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  deploy:
    uses: ./.github/workflows/strapi-common.yml
    with:
      webAppSuffix: prod
    secrets:
      azCliCreds: ${{ secrets.AZURE_CLI_CREDS }}
      publishProfile: ${{ secrets.AZURE_STRAPI_PROD_PUBLISH_PROFILE }}
