name: Strapi - Test

on:
  push:
    branches:
    - main
    paths:
    - ./frontend
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CLI_CREDS }

    - name: Set container to webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'adventistclujro-strapi-test'
        publish-profile: ${{ secrets.AZURE_WEBAPP_TEST_PUBLISH_PROFILE }}
        images: 'azscjacr.azurecr.io/azscjstrapi:1'
