name: Strapi - Deploy Test

on:
  workflow_call:
    inputs:
      webAppSuffix:
        type: string
        required: true
    secrets:
      azCliCreds:
        required: true
      publishProfile:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.azCliCreds }}

    - name: Get latest tag
      id: latestTag
      run: |
        tag=$(az acr repository show-tags -n azscjacr --repository azscjstrapi --top 1 --orderby time_desc --query "[0]" -o tsv)
        echo "Latest tag found: ${tag}"
        echo "tag=${tag}" >> $GITHUB_ENV

    - name: Set container to webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'adventistclujro-strapi-${{ inputs.webAppSuffix }}'
        publish-profile: ${{ secrets.publishProfile }}
        images: 'azscjacr.azurecr.io/azscjstrapi:${{ env.tag }}'

    - name: Set tag with image
      run: |
        tagValue='azscjacr.azurecr.io/azscjstrapi:${{ env.tag }}'
        az webapp update -g adventistclujro-${{ inputs.webAppSuffix }}-rg -n adventistclujro-strapi-${{ inputs.webAppSuffix }} --set tags.image=$tagValue
