name: Strapi - Deploy Test

on:
  push:
    branches:
    - main
    paths:
    - ./cmsstrapi
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  deploy:
    uses: ./.github/workflows/strapi-common.yml
    with:
      webAppSuffix: test
    secrets:
      azCliCreds: ${{ secrets.AZURE_CLI_CREDS }}
      publishProfile: ${{ secrets.AZURE_STRAPI_TEST_PUBLISH_PROFILE }}
