name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: docker login
        uses: docker/login-action@v1.10.0
        with:
          registry: azscjacr.azurecr.io
          username: ${{ secrets.AZURE_ACR_USER }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}
      - name: docker build
        working-directory: ./cms
        run: |
          docker build -t azscjstrapi:${{ GITHUB_RUN_ID }} .
          
      - name: docker push
        run: |
          docker push azscjacr.azurecr.io/azscjstrapi:${{ GITHUB_RUN_ID }}
      
    
