name: Strapi - Image Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: azscjacr.azurecr.io
          username: ${{ secrets.AZURE_ACR_USER }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}
      - name: docker build
        working-directory: ./cmsstrapi
        run: |
          docker build -t azscjacr.azurecr.io/azsstrapi:latest .
          docker image tag azscjacr.azurecr.io/azsstrapi:latest azscjacr.azurecr.io/azsstrapi:${{ github.run_number }}
          
      - name: docker push
        run: |
          docker push --all-tags azscjacr.azurecr.io/azsstrapi
      
    
