name: Strapi - Deploy to AZSPlatform

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      imageName: azscjacr.azurecr.io/azsstrapi
      webAppName: webapp-cms-azsplatform
    secrets:
      azCliCreds: ${{ secrets.AZURE_CLI_CREDS }}
