name: Strapi - Deploy Test

on:
  push:
    branches:
    - main
    paths:
    - ./frontend
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CLI_CREDS }}

    - name: Get latest tag
      id: latestTag
      run: |
        tag=$(az acr repository show-tags -n azscjacr --repository azscjstrapi --top 1 --orderby time_desc --query "[0]" -o tsv)
        echo "Latest tag found: ${tag}"
        echo "::set-output name=tag::${tag}"

    - name: Set container to webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'adventistclujro-strapi-test'
        publish-profile: ${{ secrets.AZURE_STRAPI_TEST_PUBLISH_PROFILE }}
        images: 'azscjacr.azurecr.io/azscjstrapi:${{ steps.latestTag.outputs.tag }}'

    - name: Set tag with image
      run: |
        tag='azscjacr.azurecr.io/azscjstrapi:${{ steps.latestTag.outputs.tag }}'
        az webapp update -g adventistclujro-test-rg -n adventistcluj-test --set tags.tagName=tagValue
