name: Strapi - Deploy to Prods

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  deploy-adventistcluj:
    uses: ./.github/workflows/deploy-template.yml
    with:
      imageName: azsstrapi
      webAppName: webapp-cms-adventistcluj
    secrets:
      azCliCreds: ${{ secrets.AZURE_CLI_CREDS }}
  deploy-brasovadventist:
    uses: ./.github/workflows/deploy-template.yml
    with:
      imageName: azsstrapi
      webAppName: webapp-cms-brasovadventist
    secrets:
      azCliCreds: ${{ secrets.AZURE_CLI_CREDS }}
