name: Web - Deploy to AZSPlatform

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  set-image-tag:
    uses: ./.github/workflows/deploy-template.yml
    with:
      imageName: azscjacr.azurecr.io/azsweb
      webAppName: webapp-frontend-azsplatform
    secrets:
      azCliCreds: ${{ secrets.AZURE_CLI_CREDS }}
