name: Web - Deploy AZSPlatform

on:
  push:
    branches:
    - main
    paths:
    - ./frontend
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  set-image-tag:
    uses: ./.github/workflows/deploy-template.yml
    with:
      containerAppName: cms-azsplatform-app
      imageName: azsstrapi
      resourceGroup: cms-azsplatform-app
    secrets:
      azCliCreds: ${{ secrets.AZURE_CLI_CREDS }}
      publishProfile: ${{ secrets.AZURE_WEBAPP_TEST_PUBLISH_PROFILE }}
