name: Web - Deploy Prods

on:
  push:
    branches:
    - main
    - containerApps
    paths:
    - ./frontend
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/webApp-common.yml
    with:
      webAppName: adventistclujro-prod
      webAppPackagePath: './backend'
      nodeVersion: '16.x'
    secrets:
      publishProfile: ${{ secrets.AZURE_WEBAPP_PROD_PUBLISH_PROFILE }}
      googleAnalytics: ${{ secrets.GOOGLE_ANALYTICS_PROD_ENV }}
