name: Web - Deploy to AZSPlatform

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  set-image-tag:
    uses: ./.github/workflows/deploy-template.yml
    with:
      containerAppName: web-azsplatform-app
      imageName: azsweb
      resourceGroup: azsplatform-rg
    secrets:
      azCliCreds: ${{ secrets.AZURE_CLI_CREDS }}
      publishProfile: ${{ secrets.AZURE_WEBAPP_TEST_PUBLISH_PROFILE }}
