name: WebApp - common

on:
  workflow_call:
    inputs:
      webAppName:
        type: string
        required: true
      webAppPackagePath:
        type: string
        required: true
      nodeVersion:
        type: string
        required: true
    secrets:
      publishProfile:
        required: true
      googleAnalytics:
        required: true
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ inputs.nodeVersion }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodeVersion }}
    - name: Install yarn
      run: |
        npm install -g yarn
    - name: Build frontend
      working-directory: './frontend'
      env: 
        REACT_APP_GOOGLE_ANALYTICS: ${{ secrets.googleAnalytics }}

      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        yarn install
        yarn run build
        yarn run test
    - name: Copy static files
      working-directory: '.'
      run: |
        mkdir -p ./backend/build
        cp -r ./frontend/build/* ./backend/build
    - name: Build backend
      working-directory: './backend'
      run: |
        yarn install
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.webAppName }}
        publish-profile: ${{ secrets.publishProfile }}
        package: ${{ inputs.webAppPackagePath }}
