name: WebApp - Test

on:
  push:
    branches:
    - main
    paths:
    - ./frontend
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/webApp-common.yml
    with:
      webAppName: adventistclujro-test
      webAppPackagePath: './backend'
      azureHost: 'https://test.adventistcluj.ro'
      nodeVersion: '16.x'
    secrets:
      publishProfile: ${{ secrets.AZURE_WEBAPP_TEST_PUBLISH_PROFILE }}
